name: custom_plugin
version: '1.0-SNAPSHOT'
main: com.gweam.custom_plugin.Custom_plugin
api-version: '1.20'
authors: [ Gweam ]
description: A self learning plugin made by gweam with no specific features
